Repository jenkinsci/ecutest-plugin, pull requests merged in 2020-11, with the labels that each got.

#243 Add GitHub action to sync issue labels
  .github/labels.yml
  .github/workflows/sync-labels.yml
Labels: chore

#246 Add GitHub action to update release drafts
  .github/workflows/codeql-analysis.yml
  .github/workflows/maven.yml
  .github/workflows/release-drafter.yml
Labels: chore

#245 Add GitHub action to check markdown links
  .github/workflows/md-link-check.yml
Labels: chore, documentation

#244 Ensure ECU-TEST 2020.4 compatibility
  README.md
  src/main/java/de/tracetronic/jenkins/plugins/ecutest/ETPlugin.java
Labels: ecu-test, feature

#247 Ensure TEST-GUIDE 1.87.0 compatibility
  README.md
  src/main/java/de/tracetronic/jenkins/plugins/ecutest/ETPlugin.java
  src/main/resources/de/tracetronic/jenkins/plugins/ecutest/report/atx/installation/config.xml
  src/test/resources/de/tracetronic/jenkins/plugins/ecutest/report/atx/installation/casc-export.yml
  src/test/resources/de/tracetronic/jenkins/plugins/ecutest/report/atx/installation/casc.yml
Labels: feature, test-guide
