Repository jenkinsci/ecutest-plugin, pull requests merged in 2020-09, with the labels that each got.

#214 Check ECU-TEST license
  docs/images/downstream_post_build_steps.png
  src/main/java/de/tracetronic/jenkins/plugins/ecutest/tool/LicenseETBuilder.java
  src/main/java/de/tracetronic/jenkins/plugins/ecutest/tool/client/ETClient.java
  src/main/java/de/tracetronic/jenkins/plugins/ecutest/tool/client/ToolClient.java
  src/main/resources/de/tracetronic/jenkins/plugins/ecutest/tool/LicenseETBuilder/config.jelly
  src/main/resources/de/tracetronic/jenkins/plugins/ecutest/tool/LicenseETBuilder/help.html
  src/main/resources/de/tracetronic/jenkins/plugins/ecutest/tool/LicenseETBuilder/help_de.html
  src/main/resources/de/tracetronic/jenkins/plugins/ecutest/tool/Messages.properties
  src/main/resources/de/tracetronic/jenkins/plugins/ecutest/tool/Messages_de.properties
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/tool/LicenseETBuilderIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/tool/LicenseETBuilderTest.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/tool/client/ETClientTest.java
Labels: ecu-test, feature

#213 Warnings NG plugin should be optional
  .idea/checkstyle-idea.xml
  src/main/java/de/tracetronic/jenkins/plugins/ecutest/extension/warnings/WarningsRecorder.java
  src/main/java/de/tracetronic/jenkins/plugins/ecutest/test/client/AbstractTestClient.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/IntegrationTestBase.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/extension/jobdsl/TestBuilderDslExtensionIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/extension/warnings/WarningsRecorderIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/report/atx/ATXPublisherIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/report/atx/pipeline/ATXPipelineIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/report/generator/ReportGeneratorPublisherIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/report/junit/JUnitPublisherIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/report/log/ETLogPublisherIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/report/ta/TraceAnalysisPublisherIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/report/tms/TMSPublisherIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/report/trf/TRFPublisherIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/test/ExportPackageBuilderIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/test/ExportProjectBuilderIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/test/ImportPackageBuilderIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/test/ImportProjectBuilderIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/test/TestFolderBuilderIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/test/TestFolderBuilderTest.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/test/TestPackageBuilderIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/test/TestPackageBuilderTest.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/test/TestProjectBuilderIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/test/TestProjectBuilderTest.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/test/client/PackageClientTest.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/test/client/ProjectClientTest.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/test/config/ExecutionConfigTest.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/tool/CacheBuilderIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/tool/StartETBuilderIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/tool/StartTSBuilderIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/tool/StopETBuilderIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/tool/StopTSBuilderIT.java
  src/test/java/de/tracetronic/jenkins/plugins/ecutest/tool/pipeline/ETPipelineIT.java
  src/test/resources/de/tracetronic/jenkins/plugins/ecutest/extension/warnings/WarningsRecorderIT/issues.json
  src/test/resources/de/tracetronic/jenkins/plugins/ecutest/test/TestFolderBuilderIT/classicStep.groovy
  src/test/resources/de/tracetronic/jenkins/plugins/ecutest/test/TestFolderBuilderIT/symbolStep.groovy
  src/test/resources/de/tracetronic/jenkins/plugins/ecutest/test/TestPackageBuilderIT/classicStep.groovy
  src/test/resources/de/tracetronic/jenkins/plugins/ecutest/test/TestPackageBuilderIT/symbolStep.groovy
  src/test/resources/de/tracetronic/jenkins/plugins/ecutest/test/TestProjectBuilderIT/classicStep.groovy
  src/test/resources/de/tracetronic/jenkins/plugins/ecutest/test/TestProjectBuilderIT/symbolStep.groovy
Labels: bug

#218 Fix encoding of Windows agent restart task
  docs/RESTART_JENKINS_AGENT.xml
Labels: documentation

#221 Inconsistent type setters for timeout property of tool builders
  src/main/java/de/tracetronic/jenkins/plugins/ecutest/tool/AbstractToolBuilder.java
Labels: bug
